language: node_js

node_js:
  - 'stable'
  - '8'
  - '6'

before_install:
  - npm i -g tslint typescript

script:
  - npm run lint
  - npm run test
  - npm run build

cache:
  directories:
    - node_modules